// Code generated by MockGen. DO NOT EDIT.
// Source: streaming.go
//
// Generated by this command:
//
//	mockgen -source=streaming.go -destination=../mocks/mock_services.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	url "net/url"
	reflect "reflect"
	time "time"

	domain "github.com/athandoan/youtube/streaming-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMetadataService is a mock of MetadataService interface.
type MockMetadataService struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataServiceMockRecorder
	isgomock struct{}
}

// MockMetadataServiceMockRecorder is the mock recorder for MockMetadataService.
type MockMetadataServiceMockRecorder struct {
	mock *MockMetadataService
}

// NewMockMetadataService creates a new mock instance.
func NewMockMetadataService(ctrl *gomock.Controller) *MockMetadataService {
	mock := &MockMetadataService{ctrl: ctrl}
	mock.recorder = &MockMetadataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataService) EXPECT() *MockMetadataServiceMockRecorder {
	return m.recorder
}

// GetVideo mocks base method.
func (m *MockMetadataService) GetVideo(ctx context.Context, id string) (*domain.VideoMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideo", ctx, id)
	ret0, _ := ret[0].(*domain.VideoMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideo indicates an expected call of GetVideo.
func (mr *MockMetadataServiceMockRecorder) GetVideo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideo", reflect.TypeOf((*MockMetadataService)(nil).GetVideo), ctx, id)
}

// MockStorageService is a mock of StorageService interface.
type MockStorageService struct {
	ctrl     *gomock.Controller
	recorder *MockStorageServiceMockRecorder
	isgomock struct{}
}

// MockStorageServiceMockRecorder is the mock recorder for MockStorageService.
type MockStorageServiceMockRecorder struct {
	mock *MockStorageService
}

// NewMockStorageService creates a new mock instance.
func NewMockStorageService(ctrl *gomock.Controller) *MockStorageService {
	mock := &MockStorageService{ctrl: ctrl}
	mock.recorder = &MockStorageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageService) EXPECT() *MockStorageServiceMockRecorder {
	return m.recorder
}

// PresignedGetObject mocks base method.
func (m *MockStorageService) PresignedGetObject(ctx context.Context, bucket, objectKey string, expiry time.Duration) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedGetObject", ctx, bucket, objectKey, expiry)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignedGetObject indicates an expected call of PresignedGetObject.
func (mr *MockStorageServiceMockRecorder) PresignedGetObject(ctx, bucket, objectKey, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedGetObject", reflect.TypeOf((*MockStorageService)(nil).PresignedGetObject), ctx, bucket, objectKey, expiry)
}

// MockStreamingUsecase is a mock of StreamingUsecase interface.
type MockStreamingUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockStreamingUsecaseMockRecorder
	isgomock struct{}
}

// MockStreamingUsecaseMockRecorder is the mock recorder for MockStreamingUsecase.
type MockStreamingUsecaseMockRecorder struct {
	mock *MockStreamingUsecase
}

// NewMockStreamingUsecase creates a new mock instance.
func NewMockStreamingUsecase(ctrl *gomock.Controller) *MockStreamingUsecase {
	mock := &MockStreamingUsecase{ctrl: ctrl}
	mock.recorder = &MockStreamingUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamingUsecase) EXPECT() *MockStreamingUsecaseMockRecorder {
	return m.recorder
}

// GetStreamURL mocks base method.
func (m *MockStreamingUsecase) GetStreamURL(ctx context.Context, videoID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamURL", ctx, videoID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamURL indicates an expected call of GetStreamURL.
func (mr *MockStreamingUsecaseMockRecorder) GetStreamURL(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamURL", reflect.TypeOf((*MockStreamingUsecase)(nil).GetStreamURL), ctx, videoID)
}
