// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/metadata/metadata.proto

package metadata

import (
	common "github.com/athandoan/youtube/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoRequest) Reset() {
	*x = GetVideoRequest{}
	mi := &file_proto_metadata_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoRequest) ProtoMessage() {}

func (x *GetVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadata_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *GetVideoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosRequest) Reset() {
	*x = ListVideosRequest{}
	mi := &file_proto_metadata_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosRequest) ProtoMessage() {}

func (x *ListVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosRequest.ProtoReflect.Descriptor instead.
func (*ListVideosRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadata_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *ListVideosRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ListVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*common.Video        `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosResponse) Reset() {
	*x = ListVideosResponse{}
	mi := &file_proto_metadata_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosResponse) ProtoMessage() {}

func (x *ListVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosResponse.ProtoReflect.Descriptor instead.
func (*ListVideosResponse) Descriptor() ([]byte, []int) {
	return file_proto_metadata_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *ListVideosResponse) GetVideos() []*common.Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

type CreateVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoRequest) Reset() {
	*x = CreateVideoRequest{}
	mi := &file_proto_metadata_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoRequest) ProtoMessage() {}

func (x *CreateVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoRequest.ProtoReflect.Descriptor instead.
func (*CreateVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadata_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *CreateVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVideoRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *CreateVideoRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type CreateVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoResponse) Reset() {
	*x = CreateVideoResponse{}
	mi := &file_proto_metadata_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoResponse) ProtoMessage() {}

func (x *CreateVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoResponse.ProtoReflect.Descriptor instead.
func (*CreateVideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_metadata_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVideoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateVideoStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoStatusRequest) Reset() {
	*x = UpdateVideoStatusRequest{}
	mi := &file_proto_metadata_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoStatusRequest) ProtoMessage() {}

func (x *UpdateVideoStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateVideoStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadata_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateVideoStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateVideoStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateVideoStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoStatusResponse) Reset() {
	*x = UpdateVideoStatusResponse{}
	mi := &file_proto_metadata_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoStatusResponse) ProtoMessage() {}

func (x *UpdateVideoStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateVideoStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_metadata_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateVideoStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_metadata_metadata_proto protoreflect.FileDescriptor

const file_proto_metadata_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/metadata/metadata.proto\x12\bmetadata\x1a\x19proto/common/common.proto\"!\n" +
	"\x0fGetVideoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\x11ListVideosRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\";\n" +
	"\x12ListVideosResponse\x12%\n" +
	"\x06videos\x18\x01 \x03(\v2\r.common.VideoR\x06videos\"a\n" +
	"\x12CreateVideoRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\"%\n" +
	"\x13CreateVideoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x18UpdateVideoStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"3\n" +
	"\x19UpdateVideoStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xba\x02\n" +
	"\x0fMetadataService\x124\n" +
	"\bGetVideo\x12\x19.metadata.GetVideoRequest\x1a\r.common.Video\x12G\n" +
	"\n" +
	"ListVideos\x12\x1b.metadata.ListVideosRequest\x1a\x1c.metadata.ListVideosResponse\x12J\n" +
	"\vCreateVideo\x12\x1c.metadata.CreateVideoRequest\x1a\x1d.metadata.CreateVideoResponse\x12\\\n" +
	"\x11UpdateVideoStatus\x12\".metadata.UpdateVideoStatusRequest\x1a#.metadata.UpdateVideoStatusResponseB-Z+github.com/athandoan/youtube/proto/metadatab\x06proto3"

var (
	file_proto_metadata_metadata_proto_rawDescOnce sync.Once
	file_proto_metadata_metadata_proto_rawDescData []byte
)

func file_proto_metadata_metadata_proto_rawDescGZIP() []byte {
	file_proto_metadata_metadata_proto_rawDescOnce.Do(func() {
		file_proto_metadata_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metadata_metadata_proto_rawDesc), len(file_proto_metadata_metadata_proto_rawDesc)))
	})
	return file_proto_metadata_metadata_proto_rawDescData
}

var file_proto_metadata_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_metadata_metadata_proto_goTypes = []any{
	(*GetVideoRequest)(nil),           // 0: metadata.GetVideoRequest
	(*ListVideosRequest)(nil),         // 1: metadata.ListVideosRequest
	(*ListVideosResponse)(nil),        // 2: metadata.ListVideosResponse
	(*CreateVideoRequest)(nil),        // 3: metadata.CreateVideoRequest
	(*CreateVideoResponse)(nil),       // 4: metadata.CreateVideoResponse
	(*UpdateVideoStatusRequest)(nil),  // 5: metadata.UpdateVideoStatusRequest
	(*UpdateVideoStatusResponse)(nil), // 6: metadata.UpdateVideoStatusResponse
	(*common.Video)(nil),              // 7: common.Video
}
var file_proto_metadata_metadata_proto_depIdxs = []int32{
	7, // 0: metadata.ListVideosResponse.videos:type_name -> common.Video
	0, // 1: metadata.MetadataService.GetVideo:input_type -> metadata.GetVideoRequest
	1, // 2: metadata.MetadataService.ListVideos:input_type -> metadata.ListVideosRequest
	3, // 3: metadata.MetadataService.CreateVideo:input_type -> metadata.CreateVideoRequest
	5, // 4: metadata.MetadataService.UpdateVideoStatus:input_type -> metadata.UpdateVideoStatusRequest
	7, // 5: metadata.MetadataService.GetVideo:output_type -> common.Video
	2, // 6: metadata.MetadataService.ListVideos:output_type -> metadata.ListVideosResponse
	4, // 7: metadata.MetadataService.CreateVideo:output_type -> metadata.CreateVideoResponse
	6, // 8: metadata.MetadataService.UpdateVideoStatus:output_type -> metadata.UpdateVideoStatusResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_metadata_metadata_proto_init() }
func file_proto_metadata_metadata_proto_init() {
	if File_proto_metadata_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metadata_metadata_proto_rawDesc), len(file_proto_metadata_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metadata_metadata_proto_goTypes,
		DependencyIndexes: file_proto_metadata_metadata_proto_depIdxs,
		MessageInfos:      file_proto_metadata_metadata_proto_msgTypes,
	}.Build()
	File_proto_metadata_metadata_proto = out.File
	file_proto_metadata_metadata_proto_goTypes = nil
	file_proto_metadata_metadata_proto_depIdxs = nil
}
