// Code generated by MockGen. DO NOT EDIT.
// Source: gateway.go
//
// Generated by this command:
//
//	mockgen -source=gateway.go -destination=../mocks/mock_services.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	common "github.com/athandoan/youtube/proto/common"
	upload "github.com/athandoan/youtube/proto/upload"
	gomock "go.uber.org/mock/gomock"
)

// MockMetadataService is a mock of MetadataService interface.
type MockMetadataService struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataServiceMockRecorder
	isgomock struct{}
}

// MockMetadataServiceMockRecorder is the mock recorder for MockMetadataService.
type MockMetadataServiceMockRecorder struct {
	mock *MockMetadataService
}

// NewMockMetadataService creates a new mock instance.
func NewMockMetadataService(ctrl *gomock.Controller) *MockMetadataService {
	mock := &MockMetadataService{ctrl: ctrl}
	mock.recorder = &MockMetadataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataService) EXPECT() *MockMetadataServiceMockRecorder {
	return m.recorder
}

// ListVideos mocks base method.
func (m *MockMetadataService) ListVideos(ctx context.Context, query string) ([]*common.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVideos", ctx, query)
	ret0, _ := ret[0].([]*common.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVideos indicates an expected call of ListVideos.
func (mr *MockMetadataServiceMockRecorder) ListVideos(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVideos", reflect.TypeOf((*MockMetadataService)(nil).ListVideos), ctx, query)
}

// MockUploadService is a mock of UploadService interface.
type MockUploadService struct {
	ctrl     *gomock.Controller
	recorder *MockUploadServiceMockRecorder
	isgomock struct{}
}

// MockUploadServiceMockRecorder is the mock recorder for MockUploadService.
type MockUploadServiceMockRecorder struct {
	mock *MockUploadService
}

// NewMockUploadService creates a new mock instance.
func NewMockUploadService(ctrl *gomock.Controller) *MockUploadService {
	mock := &MockUploadService{ctrl: ctrl}
	mock.recorder = &MockUploadServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadService) EXPECT() *MockUploadServiceMockRecorder {
	return m.recorder
}

// CompleteUpload mocks base method.
func (m *MockUploadService) CompleteUpload(ctx context.Context, videoID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteUpload", ctx, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteUpload indicates an expected call of CompleteUpload.
func (mr *MockUploadServiceMockRecorder) CompleteUpload(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteUpload", reflect.TypeOf((*MockUploadService)(nil).CompleteUpload), ctx, videoID)
}

// InitUpload mocks base method.
func (m *MockUploadService) InitUpload(ctx context.Context, title, filename string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitUpload", ctx, title, filename)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InitUpload indicates an expected call of InitUpload.
func (mr *MockUploadServiceMockRecorder) InitUpload(ctx, title, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitUpload", reflect.TypeOf((*MockUploadService)(nil).InitUpload), ctx, title, filename)
}

// MockStreamingService is a mock of StreamingService interface.
type MockStreamingService struct {
	ctrl     *gomock.Controller
	recorder *MockStreamingServiceMockRecorder
	isgomock struct{}
}

// MockStreamingServiceMockRecorder is the mock recorder for MockStreamingService.
type MockStreamingServiceMockRecorder struct {
	mock *MockStreamingService
}

// NewMockStreamingService creates a new mock instance.
func NewMockStreamingService(ctrl *gomock.Controller) *MockStreamingService {
	mock := &MockStreamingService{ctrl: ctrl}
	mock.recorder = &MockStreamingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamingService) EXPECT() *MockStreamingServiceMockRecorder {
	return m.recorder
}

// GetStreamURL mocks base method.
func (m *MockStreamingService) GetStreamURL(ctx context.Context, videoID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamURL", ctx, videoID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamURL indicates an expected call of GetStreamURL.
func (mr *MockStreamingServiceMockRecorder) GetStreamURL(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamURL", reflect.TypeOf((*MockStreamingService)(nil).GetStreamURL), ctx, videoID)
}

// MockGatewayUsecase is a mock of GatewayUsecase interface.
type MockGatewayUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayUsecaseMockRecorder
	isgomock struct{}
}

// MockGatewayUsecaseMockRecorder is the mock recorder for MockGatewayUsecase.
type MockGatewayUsecaseMockRecorder struct {
	mock *MockGatewayUsecase
}

// NewMockGatewayUsecase creates a new mock instance.
func NewMockGatewayUsecase(ctrl *gomock.Controller) *MockGatewayUsecase {
	mock := &MockGatewayUsecase{ctrl: ctrl}
	mock.recorder = &MockGatewayUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayUsecase) EXPECT() *MockGatewayUsecaseMockRecorder {
	return m.recorder
}

// CompleteUpload mocks base method.
func (m *MockGatewayUsecase) CompleteUpload(ctx context.Context, videoID string) (*upload.CompleteUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteUpload", ctx, videoID)
	ret0, _ := ret[0].(*upload.CompleteUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteUpload indicates an expected call of CompleteUpload.
func (mr *MockGatewayUsecaseMockRecorder) CompleteUpload(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteUpload", reflect.TypeOf((*MockGatewayUsecase)(nil).CompleteUpload), ctx, videoID)
}

// GetStreamURL mocks base method.
func (m *MockGatewayUsecase) GetStreamURL(ctx context.Context, videoID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamURL", ctx, videoID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamURL indicates an expected call of GetStreamURL.
func (mr *MockGatewayUsecaseMockRecorder) GetStreamURL(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamURL", reflect.TypeOf((*MockGatewayUsecase)(nil).GetStreamURL), ctx, videoID)
}

// InitUpload mocks base method.
func (m *MockGatewayUsecase) InitUpload(ctx context.Context, title, filename string) (*upload.InitUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitUpload", ctx, title, filename)
	ret0, _ := ret[0].(*upload.InitUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitUpload indicates an expected call of InitUpload.
func (mr *MockGatewayUsecaseMockRecorder) InitUpload(ctx, title, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitUpload", reflect.TypeOf((*MockGatewayUsecase)(nil).InitUpload), ctx, title, filename)
}

// ListVideos mocks base method.
func (m *MockGatewayUsecase) ListVideos(ctx context.Context, query string) ([]*common.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVideos", ctx, query)
	ret0, _ := ret[0].([]*common.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVideos indicates an expected call of ListVideos.
func (mr *MockGatewayUsecaseMockRecorder) ListVideos(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVideos", reflect.TypeOf((*MockGatewayUsecase)(nil).ListVideos), ctx, query)
}
