// Code generated by MockGen. DO NOT EDIT.
// Source: upload.go
//
// Generated by this command:
//
//	mockgen -source=upload.go -destination=../mocks/mock_services.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	url "net/url"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStorageService is a mock of StorageService interface.
type MockStorageService struct {
	ctrl     *gomock.Controller
	recorder *MockStorageServiceMockRecorder
	isgomock struct{}
}

// MockStorageServiceMockRecorder is the mock recorder for MockStorageService.
type MockStorageServiceMockRecorder struct {
	mock *MockStorageService
}

// NewMockStorageService creates a new mock instance.
func NewMockStorageService(ctrl *gomock.Controller) *MockStorageService {
	mock := &MockStorageService{ctrl: ctrl}
	mock.recorder = &MockStorageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageService) EXPECT() *MockStorageServiceMockRecorder {
	return m.recorder
}

// PresignedPutObject mocks base method.
func (m *MockStorageService) PresignedPutObject(ctx context.Context, bucket, objectKey string, expiry time.Duration) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedPutObject", ctx, bucket, objectKey, expiry)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignedPutObject indicates an expected call of PresignedPutObject.
func (mr *MockStorageServiceMockRecorder) PresignedPutObject(ctx, bucket, objectKey, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedPutObject", reflect.TypeOf((*MockStorageService)(nil).PresignedPutObject), ctx, bucket, objectKey, expiry)
}

// MockMetadataService is a mock of MetadataService interface.
type MockMetadataService struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataServiceMockRecorder
	isgomock struct{}
}

// MockMetadataServiceMockRecorder is the mock recorder for MockMetadataService.
type MockMetadataServiceMockRecorder struct {
	mock *MockMetadataService
}

// NewMockMetadataService creates a new mock instance.
func NewMockMetadataService(ctrl *gomock.Controller) *MockMetadataService {
	mock := &MockMetadataService{ctrl: ctrl}
	mock.recorder = &MockMetadataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataService) EXPECT() *MockMetadataServiceMockRecorder {
	return m.recorder
}

// CreateVideo mocks base method.
func (m *MockMetadataService) CreateVideo(ctx context.Context, title, bucket, objectKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVideo", ctx, title, bucket, objectKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVideo indicates an expected call of CreateVideo.
func (mr *MockMetadataServiceMockRecorder) CreateVideo(ctx, title, bucket, objectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVideo", reflect.TypeOf((*MockMetadataService)(nil).CreateVideo), ctx, title, bucket, objectKey)
}

// UpdateVideoStatus mocks base method.
func (m *MockMetadataService) UpdateVideoStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVideoStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVideoStatus indicates an expected call of UpdateVideoStatus.
func (mr *MockMetadataServiceMockRecorder) UpdateVideoStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVideoStatus", reflect.TypeOf((*MockMetadataService)(nil).UpdateVideoStatus), ctx, id, status)
}

// MockUploadUsecase is a mock of UploadUsecase interface.
type MockUploadUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUploadUsecaseMockRecorder
	isgomock struct{}
}

// MockUploadUsecaseMockRecorder is the mock recorder for MockUploadUsecase.
type MockUploadUsecaseMockRecorder struct {
	mock *MockUploadUsecase
}

// NewMockUploadUsecase creates a new mock instance.
func NewMockUploadUsecase(ctrl *gomock.Controller) *MockUploadUsecase {
	mock := &MockUploadUsecase{ctrl: ctrl}
	mock.recorder = &MockUploadUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadUsecase) EXPECT() *MockUploadUsecaseMockRecorder {
	return m.recorder
}

// CompleteUpload mocks base method.
func (m *MockUploadUsecase) CompleteUpload(ctx context.Context, videoID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteUpload", ctx, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteUpload indicates an expected call of CompleteUpload.
func (mr *MockUploadUsecaseMockRecorder) CompleteUpload(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteUpload", reflect.TypeOf((*MockUploadUsecase)(nil).CompleteUpload), ctx, videoID)
}

// InitUpload mocks base method.
func (m *MockUploadUsecase) InitUpload(ctx context.Context, title, filename string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitUpload", ctx, title, filename)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InitUpload indicates an expected call of InitUpload.
func (mr *MockUploadUsecaseMockRecorder) InitUpload(ctx, title, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitUpload", reflect.TypeOf((*MockUploadUsecase)(nil).InitUpload), ctx, title, filename)
}
