// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/streaming/streaming.proto

package streaming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStreamURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamURLRequest) Reset() {
	*x = GetStreamURLRequest{}
	mi := &file_proto_streaming_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamURLRequest) ProtoMessage() {}

func (x *GetStreamURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamURLRequest.ProtoReflect.Descriptor instead.
func (*GetStreamURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_streaming_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *GetStreamURLRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type GetStreamURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamURLResponse) Reset() {
	*x = GetStreamURLResponse{}
	mi := &file_proto_streaming_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamURLResponse) ProtoMessage() {}

func (x *GetStreamURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamURLResponse.ProtoReflect.Descriptor instead.
func (*GetStreamURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_streaming_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *GetStreamURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_proto_streaming_streaming_proto protoreflect.FileDescriptor

const file_proto_streaming_streaming_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/streaming/streaming.proto\x12\tstreaming\"0\n" +
	"\x13GetStreamURLRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"(\n" +
	"\x14GetStreamURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2c\n" +
	"\x10StreamingService\x12O\n" +
	"\fGetStreamURL\x12\x1e.streaming.GetStreamURLRequest\x1a\x1f.streaming.GetStreamURLResponseB.Z,github.com/athandoan/youtube/proto/streamingb\x06proto3"

var (
	file_proto_streaming_streaming_proto_rawDescOnce sync.Once
	file_proto_streaming_streaming_proto_rawDescData []byte
)

func file_proto_streaming_streaming_proto_rawDescGZIP() []byte {
	file_proto_streaming_streaming_proto_rawDescOnce.Do(func() {
		file_proto_streaming_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_streaming_streaming_proto_rawDesc), len(file_proto_streaming_streaming_proto_rawDesc)))
	})
	return file_proto_streaming_streaming_proto_rawDescData
}

var file_proto_streaming_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_streaming_streaming_proto_goTypes = []any{
	(*GetStreamURLRequest)(nil),  // 0: streaming.GetStreamURLRequest
	(*GetStreamURLResponse)(nil), // 1: streaming.GetStreamURLResponse
}
var file_proto_streaming_streaming_proto_depIdxs = []int32{
	0, // 0: streaming.StreamingService.GetStreamURL:input_type -> streaming.GetStreamURLRequest
	1, // 1: streaming.StreamingService.GetStreamURL:output_type -> streaming.GetStreamURLResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_streaming_streaming_proto_init() }
func file_proto_streaming_streaming_proto_init() {
	if File_proto_streaming_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_streaming_streaming_proto_rawDesc), len(file_proto_streaming_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_streaming_streaming_proto_goTypes,
		DependencyIndexes: file_proto_streaming_streaming_proto_depIdxs,
		MessageInfos:      file_proto_streaming_streaming_proto_msgTypes,
	}.Build()
	File_proto_streaming_streaming_proto = out.File
	file_proto_streaming_streaming_proto_goTypes = nil
	file_proto_streaming_streaming_proto_depIdxs = nil
}
