// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/upload/upload.proto

package upload

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitUploadRequest) Reset() {
	*x = InitUploadRequest{}
	mi := &file_proto_upload_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitUploadRequest) ProtoMessage() {}

func (x *InitUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitUploadRequest.ProtoReflect.Descriptor instead.
func (*InitUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_upload_upload_proto_rawDescGZIP(), []int{0}
}

func (x *InitUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *InitUploadRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type InitUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	PresignedUrl  string                 `protobuf:"bytes,2,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitUploadResponse) Reset() {
	*x = InitUploadResponse{}
	mi := &file_proto_upload_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitUploadResponse) ProtoMessage() {}

func (x *InitUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitUploadResponse.ProtoReflect.Descriptor instead.
func (*InitUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_upload_upload_proto_rawDescGZIP(), []int{1}
}

func (x *InitUploadResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *InitUploadResponse) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

type CompleteUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadRequest) Reset() {
	*x = CompleteUploadRequest{}
	mi := &file_proto_upload_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadRequest) ProtoMessage() {}

func (x *CompleteUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_upload_upload_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteUploadRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type CompleteUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteUploadResponse) Reset() {
	*x = CompleteUploadResponse{}
	mi := &file_proto_upload_upload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteUploadResponse) ProtoMessage() {}

func (x *CompleteUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_upload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteUploadResponse.ProtoReflect.Descriptor instead.
func (*CompleteUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_upload_upload_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteUploadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_upload_upload_proto protoreflect.FileDescriptor

const file_proto_upload_upload_proto_rawDesc = "" +
	"\n" +
	"\x19proto/upload/upload.proto\x12\x06upload\"E\n" +
	"\x11InitUploadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"T\n" +
	"\x12InitUploadResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12#\n" +
	"\rpresigned_url\x18\x02 \x01(\tR\fpresignedUrl\"2\n" +
	"\x15CompleteUploadRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"0\n" +
	"\x16CompleteUploadResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xa5\x01\n" +
	"\rUploadService\x12C\n" +
	"\n" +
	"InitUpload\x12\x19.upload.InitUploadRequest\x1a\x1a.upload.InitUploadResponse\x12O\n" +
	"\x0eCompleteUpload\x12\x1d.upload.CompleteUploadRequest\x1a\x1e.upload.CompleteUploadResponseB+Z)github.com/athandoan/youtube/proto/uploadb\x06proto3"

var (
	file_proto_upload_upload_proto_rawDescOnce sync.Once
	file_proto_upload_upload_proto_rawDescData []byte
)

func file_proto_upload_upload_proto_rawDescGZIP() []byte {
	file_proto_upload_upload_proto_rawDescOnce.Do(func() {
		file_proto_upload_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_upload_upload_proto_rawDesc), len(file_proto_upload_upload_proto_rawDesc)))
	})
	return file_proto_upload_upload_proto_rawDescData
}

var file_proto_upload_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_upload_upload_proto_goTypes = []any{
	(*InitUploadRequest)(nil),      // 0: upload.InitUploadRequest
	(*InitUploadResponse)(nil),     // 1: upload.InitUploadResponse
	(*CompleteUploadRequest)(nil),  // 2: upload.CompleteUploadRequest
	(*CompleteUploadResponse)(nil), // 3: upload.CompleteUploadResponse
}
var file_proto_upload_upload_proto_depIdxs = []int32{
	0, // 0: upload.UploadService.InitUpload:input_type -> upload.InitUploadRequest
	2, // 1: upload.UploadService.CompleteUpload:input_type -> upload.CompleteUploadRequest
	1, // 2: upload.UploadService.InitUpload:output_type -> upload.InitUploadResponse
	3, // 3: upload.UploadService.CompleteUpload:output_type -> upload.CompleteUploadResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_upload_upload_proto_init() }
func file_proto_upload_upload_proto_init() {
	if File_proto_upload_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_upload_upload_proto_rawDesc), len(file_proto_upload_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_upload_upload_proto_goTypes,
		DependencyIndexes: file_proto_upload_upload_proto_depIdxs,
		MessageInfos:      file_proto_upload_upload_proto_msgTypes,
	}.Build()
	File_proto_upload_upload_proto = out.File
	file_proto_upload_upload_proto_goTypes = nil
	file_proto_upload_upload_proto_depIdxs = nil
}
